apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: mem-leak-TARGET
  namespace: boutique
spec:
  mode: one
  selector:
    namespaces:
      - boutique
    labelSelectors:
      app: TARGET_SERVICE
  stressors:
    memory:
      workers: 1
      size: "256MB"
  duration: "DURATION_VALUE"
